/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ESOFT
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bo1_btn = new javax.swing.JButton();
        bt04_btn = new javax.swing.JButton();
        bt07_btn = new javax.swing.JButton();
        bt02_btn = new javax.swing.JButton();
        bt05_btn = new javax.swing.JButton();
        bt08_btn = new javax.swing.JButton();
        bt03_btn = new javax.swing.JButton();
        bt06_btn = new javax.swing.JButton();
        bt09_btn = new javax.swing.JButton();
        txt_field = new javax.swing.JTextField();
        Btnadd = new javax.swing.JButton();
        Btnminus = new javax.swing.JButton();
        bt00_btn = new javax.swing.JButton();
        btnDOT_btn = new javax.swing.JButton();
        BtnMUl = new javax.swing.JButton();
        btEQ_btn = new javax.swing.JButton();
        Btndivide = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bo1_btn.setBackground(new java.awt.Color(255, 255, 153));
        bo1_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bo1_btn.setText("1");
        bo1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bo1_btnActionPerformed(evt);
            }
        });

        bt04_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt04_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt04_btn.setText("4");
        bt04_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt04_btnActionPerformed(evt);
            }
        });

        bt07_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt07_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt07_btn.setText("7");
        bt07_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt07_btnActionPerformed(evt);
            }
        });

        bt02_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt02_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt02_btn.setText("2");
        bt02_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt02_btnActionPerformed(evt);
            }
        });

        bt05_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt05_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt05_btn.setText("5");
        bt05_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt05_btnActionPerformed(evt);
            }
        });

        bt08_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt08_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt08_btn.setText("8");
        bt08_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt08_btnActionPerformed(evt);
            }
        });

        bt03_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt03_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt03_btn.setText("3");
        bt03_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt03_btnActionPerformed(evt);
            }
        });

        bt06_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt06_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt06_btn.setText("6");
        bt06_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt06_btnActionPerformed(evt);
            }
        });

        bt09_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt09_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt09_btn.setText("9");
        bt09_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt09_btnActionPerformed(evt);
            }
        });

        Btnadd.setBackground(new java.awt.Color(255, 204, 204));
        Btnadd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btnadd.setText("+");
        Btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaddActionPerformed(evt);
            }
        });

        Btnminus.setBackground(new java.awt.Color(255, 204, 204));
        Btnminus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btnminus.setText("-");
        Btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnminusActionPerformed(evt);
            }
        });

        bt00_btn.setBackground(new java.awt.Color(255, 255, 153));
        bt00_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt00_btn.setText("0");
        bt00_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt00_btnActionPerformed(evt);
            }
        });

        btnDOT_btn.setBackground(new java.awt.Color(255, 255, 153));
        btnDOT_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDOT_btn.setText(".");
        btnDOT_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOT_btnActionPerformed(evt);
            }
        });

        BtnMUl.setBackground(new java.awt.Color(255, 204, 204));
        BtnMUl.setText("*");
        BtnMUl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMUlActionPerformed(evt);
            }
        });

        btEQ_btn.setBackground(new java.awt.Color(204, 255, 204));
        btEQ_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEQ_btn.setText("=");
        btEQ_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEQ_btnActionPerformed(evt);
            }
        });

        Btndivide.setBackground(new java.awt.Color(255, 204, 204));
        Btndivide.setFont(new java.awt.Font("Tekton Pro", 1, 11)); // NOI18N
        Btndivide.setText("/");
        Btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndivideActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton18.setText("AC");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(255, 153, 0));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton19.setText("C");

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("          CALCULATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bt00_btn)
                                            .addComponent(bt07_btn)
                                            .addComponent(bt04_btn))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt08_btn)
                                            .addComponent(btnDOT_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt05_btn)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bo1_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt02_btn)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bt06_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt03_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btEQ_btn)
                                    .addComponent(bt09_btn))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btnminus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(BtnMUl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btndivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txt_field, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnadd)
                    .addComponent(bt03_btn)
                    .addComponent(bt02_btn)
                    .addComponent(bo1_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt04_btn)
                    .addComponent(bt05_btn)
                    .addComponent(bt06_btn)
                    .addComponent(Btnminus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMUl)
                    .addComponent(bt09_btn)
                    .addComponent(bt08_btn)
                    .addComponent(bt07_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt00_btn)
                    .addComponent(btnDOT_btn)
                    .addComponent(btEQ_btn)
                    .addComponent(Btndivide, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEQ_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEQ_btnActionPerformed

        if (ope.equals("+")) {
            
            double ans1 = numx + Double.valueOf(txt_field.getText());
            txt_field.setText(String.valueOf(ans1));
        } else if (ope.equals("-")) {
          
            double ans2 = numx - Double.valueOf(txt_field.getText());
            txt_field.setText(String.valueOf(ans2));

        }else if(ope.equals("*")){
        
            double ans3=numx * Double.valueOf(txt_field.getText());
            txt_field.setText(String.valueOf(ans3));
        
        }else if(ope.equals("/")){
        
            double ans4=numx +Double.valueOf(txt_field.getText());
            txt_field.setText(String.valueOf(ans4));
        }
        


    }//GEN-LAST:event_btEQ_btnActionPerformed

    private void bo1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bo1_btnActionPerformed
        String num1 = txt_field.getText();
        txt_field.setText(num1 + "1");
    }//GEN-LAST:event_bo1_btnActionPerformed

    private void bt02_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt02_btnActionPerformed
        String num2 = txt_field.getText();
        txt_field.setText(num2 + "2");
    }//GEN-LAST:event_bt02_btnActionPerformed

    private void bt03_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt03_btnActionPerformed
        String num3 = txt_field.getText();
        txt_field.setText(num3 + "3");
    }//GEN-LAST:event_bt03_btnActionPerformed

    private void bt04_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt04_btnActionPerformed
        String num4 = txt_field.getText();
        txt_field.setText(num4 + "4");
    }//GEN-LAST:event_bt04_btnActionPerformed

    private void bt05_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt05_btnActionPerformed
        String num5 = txt_field.getText();
        txt_field.setText(num5 + "5");
    }//GEN-LAST:event_bt05_btnActionPerformed

    private void bt06_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt06_btnActionPerformed
        String num6 = txt_field.getText();
        txt_field.setText(num6 + "6");
    }//GEN-LAST:event_bt06_btnActionPerformed

    private void bt07_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt07_btnActionPerformed
        String num7 = txt_field.getText();
        txt_field.setText(num7 + "7");
    }//GEN-LAST:event_bt07_btnActionPerformed

    private void bt08_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt08_btnActionPerformed
        String num8 = txt_field.getText();
        txt_field.setText(num8 + "8");
    }//GEN-LAST:event_bt08_btnActionPerformed

    private void bt09_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt09_btnActionPerformed
        String num9 = txt_field.getText();
        txt_field.setText(num9 + "9");
    }//GEN-LAST:event_bt09_btnActionPerformed

    private void bt00_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt00_btnActionPerformed
        String num0 = txt_field.getText();
        txt_field.setText(num0 + "0");
    }//GEN-LAST:event_bt00_btnActionPerformed

    private void btnDOT_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOT_btnActionPerformed
        String numd = txt_field.getText();
        txt_field.setText(numd + ".");
    }//GEN-LAST:event_btnDOT_btnActionPerformed
    double numx;
    String ope;
    private void BtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaddActionPerformed
        numx = Double.valueOf(txt_field.getText());
        txt_field.setText("");
        ope = "+";

    }//GEN-LAST:event_BtnaddActionPerformed

    private void BtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnminusActionPerformed
        numx = Double.valueOf(txt_field.getText());
        txt_field.setText("");
        ope = "-";
    }//GEN-LAST:event_BtnminusActionPerformed

    private void BtnMUlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMUlActionPerformed
        numx = Double.valueOf(txt_field.getText());
        txt_field.setText("");
        ope = "*";
        
    }//GEN-LAST:event_BtnMUlActionPerformed

    private void BtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndivideActionPerformed
        numx = Double.valueOf(txt_field.getText());
        txt_field.setText("");
        ope = "/";
        
    }//GEN-LAST:event_BtndivideActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        txt_field.setText("");
        ope ="";
        numx=0.0;
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMUl;
    private javax.swing.JButton Btnadd;
    private javax.swing.JButton Btndivide;
    private javax.swing.JButton Btnminus;
    private javax.swing.JButton bo1_btn;
    private javax.swing.JButton bt00_btn;
    private javax.swing.JButton bt02_btn;
    private javax.swing.JButton bt03_btn;
    private javax.swing.JButton bt04_btn;
    private javax.swing.JButton bt05_btn;
    private javax.swing.JButton bt06_btn;
    private javax.swing.JButton bt07_btn;
    private javax.swing.JButton bt08_btn;
    private javax.swing.JButton bt09_btn;
    private javax.swing.JButton btEQ_btn;
    private javax.swing.JButton btnDOT_btn;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_field;
    // End of variables declaration//GEN-END:variables
}
